USE hr;

--SELECT SIMPLES
SELECT * FROM LOCATIONS;
SELECT * FROM DEPARTMENTS;
SELECT * FROM JOBS;
SELECT * FROM COUNTRIES;

-- selecionando colunas
SELECT DEPARTMENT_ID, DEPARTMENT_NAME FROM DEPARTMENTS;

SELECT * FROM EMPLOYEES;
-- pegar apenas o first_name, email, jobs_id
SELECT FIRST_NAME, EMAIL, JOB_ID FROM EMPLOYEES;

--apelidando campos
SELECT FIRST_NAME AS "NOME", EMAIL AS "E-MAIL", JOB_ID AS "CODIGO DO CARGO" FROM EMPLOYEES;

SELECT d.DEPARTMENT_ID AS "ID DO DEPARTAMENTO", d.DEPARTMENT_NAME AS "NOME DO DEPARTAMENTO", d.LOCATION_ID, d.LOCATION_ID, d.MANAGER_ID FROM DEPARTMENTS d;

-- CRIAR BANCO DE DADOS
CREATE DATABASE BET7FST4;

USE BET7FST4;
--CRIAÇÃO DE TABELA
CREATE TABLE cadastro
(
nome VARCHAR(30),
sobrenome VARCHAR(30),
salario MONEY,
endereco VARCHAR(30),
dt_cadastro DATE
);

INSERT INTO cadastro VALUES ('MARCELO','DINIZ',1000,'PIRACEMA', SYSDATETIME());
SELECT * FROM cadastro; 
